### ISSUE TITLE
Project Name?

### ISSUE THREAD

**Issue by SommerEngineering** [SommerEngineering/ModularMining#7]
We need a project name and a clear abbreviation. The abbreviation could then be used as a prefix or postfix for all repositories to clarify their affiliation. Once a decision has been made, this repository should also be renamed.

**Comment by atix1906** [comment]
What about MiSA as abbreviation? So we can call it "Misa".

**Comment by SommerEngineering** [comment]
The idea was to give the project an independent name. So ... Microservices Architecture is a common label for such architectures. Maybe "Micro Platform for Data Science" and "MPDS"?

**Comment by atix1906** [comment]
Sure, but it would prefer a more pleasing call name such as "MiPDaS", any thoughts?

**Comment by SommerEngineering** [comment]
After a brain storming with colleagues, we agreed on the name `ModularMining` or short `MM`.
